services:
  app:
    build: .
    image: fastapi-structure-image
    container_name: fastapi-structure-app
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    container_name: fastapi-structure-db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - fastapi-structure-volume:/var/lib/postgresql/data
volumes:
  fastapi-structure-volume:
    name: "fastapi-structure-volume"
