"""initial_migration

Revision ID: 06ed89ede9a9
Revises:
Create Date: 2026-04-13 17:27:20.203919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "06ed89ede9a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="accounts",
    )
    op.create_index(
        op.f("ix_accounts_user_email"),
        "user",
        ["email"],
        unique=True,
        schema="accounts",
    )
    op.create_index(
        op.f("ix_accounts_user_google_id"),
        "user",
        ["google_id"],
        unique=False,
        schema="accounts",
    )
    op.create_index(
        op.f("ix_accounts_user_id"), "user", ["id"], unique=False, schema="accounts"
    )
    op.create_index(
        op.f("ix_accounts_user_username"),
        "user",
        ["username"],
        unique=True,
        schema="accounts",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_accounts_user_username"), table_name="user", schema="accounts"
    )
    op.drop_index(op.f("ix_accounts_user_id"), table_name="user", schema="accounts")
    op.drop_index(
        op.f("ix_accounts_user_google_id"), table_name="user", schema="accounts"
    )
    op.drop_index(op.f("ix_accounts_user_email"), table_name="user", schema="accounts")
    op.drop_table("user", schema="accounts")
    # ### end Alembic commands ###
