"""Initial models

Revision ID: 3de3653bdb4c
Revises: 
Create Date: 2026-01-26 22:10:24.325363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3de3653bdb4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_id'), 'user', ['id'], unique=False, schema='auth')
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_account_id'), 'account', ['id'], unique=False, schema='accounts')
    op.create_table('inversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inversions'
    )
    op.create_index(op.f('ix_inversions_inversion_id'), 'inversion', ['id'], unique=False, schema='inversions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inversions_inversion_id'), table_name='inversion', schema='inversions')
    op.drop_table('inversion', schema='inversions')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='account', schema='accounts')
    op.drop_table('account', schema='accounts')
    op.drop_index(op.f('ix_auth_user_id'), table_name='user', schema='auth')
    op.drop_table('user', schema='auth')
    # ### end Alembic commands ###
