"""adding_notes

Revision ID: a7b1f15f4f6a
Revises: 06ed89ede9a9
Create Date: 2026-04-15 21:45:37.797795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a7b1f15f4f6a"
down_revision: Union[str, Sequence[str], None] = "06ed89ede9a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="notes",
    )
    op.create_index(
        op.f("ix_notes_note_id"), "note", ["id"], unique=False, schema="notes"
    )
    op.create_index(
        op.f("ix_notes_note_title"), "note", ["title"], unique=False, schema="notes"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_note_title"), table_name="note", schema="notes")
    op.drop_index(op.f("ix_notes_note_id"), table_name="note", schema="notes")
    op.drop_table("note", schema="notes")
    # ### end Alembic commands ###
